finished app
TheCSharpAcademy/CodeReviews.Console.Flashcards pull request #124
Opened 2024-12-20 20:52 UTC by iamnikitakostin

Hi,

Just finished the app.
Please, be harsh on the review.
Also, not sure if I followed the best practices for the DB connection, as SQL connection seems to be different from SQLITE.
If not, please correct me, and I will re-do and resubmit.

Thank you!

2024-12-24 11:05 UTC, chrisjamiecarter requested changes
Hey @iamnikitakostin 👋,

Excellent work on your Flashcards project submission 🎉!

I have performed a peer review. Review/ignore any comments as you wish.

🟡 **Back options exits app**
In `Manage Stacks` and `Manage Flash Cards` selecting back exits the app instead of going back to the main menu. This may be intended behaviour? But is bad UX imo.

🟠 **Edit Options do not Work**
Selecting edit on Stack or Flashcard gives message saying updated successfully but without prompting for user input on what the update should be.

***

However, your project has the following issues 🔴 !
Please revisit to try understand and fix these issues 🔧 , as they relate to the projects requirements and they block my approval.

🔴 **Study with no Stacks**
Throws an exception.

🔴 **Stack names need to be Unique**
![image](https://github.com/user-attachments/assets/378b479c-d8f2-4637-ba86-c2ff7814097d)

***

Feel free to reach out if you have any questions or if you'd like to collaborate further on any of these points 🆘 .

I will go ahead and wait for you to make your changes, commit and push (which will then notify me) 😊 !

Thanks,
@chrisjamiecarter 👍

2024-12-24 21:23 UTC, iamnikitakostin commented on Flashcards.iamnikitakostin/FlashCards/FlashCards/Data/DataContext.cs
> +        protected override void OnModelCreating(ModelBuilder modelBuilder)
Hi Chris,

Thank you so much for the review!
I have fixed all the points you have outlined.
Could you please let me know if my app's structure is good?
I was trying to simulate the structure of a web-api app.

My apologies for submitting the app with that many errors initially.

Thank you,
Nikita

2024-12-27 17:13 UTC, chrisjamiecarter approved these changes
Hey @iamnikitakostin 👋,

Fantastic job getting your updates pushed through 💪 


⭐ Your project now fulfills all the requirements.

I will go ahead and mark as approved, keep up the excellent work on the next projects! 😊

Best regards,
@chrisjamiecarter 👍

2024-12-27 17:13 UTC, chrisjamiecarter commented on Flashcards.iamnikitakostin/FlashCards/FlashCards/Controllers/ConsoleController.cs
> +namespace FlashCards.Controllers;
🟢 **File-Scoped Namespaces**

💡 Although, remember to leave a blank line between namespace and class

2024-12-27 17:13 UTC, chrisjamiecarter commented on Flashcards.iamnikitakostin/FlashCards/FlashCards/Program.cs
> +        IConfiguration config = new ConfigurationBuilder()
🟢 **Configuration Settings**

🥇

2024-12-27 17:14 UTC, closed without merging