Finished FlashCards
TheCSharpAcademy/CodeReviews.Console.Flashcards pull request #38
Opened 2023-12-23 09:40 UTC by ManuelE-Osorio

Finished the project. There are improvement points as shown in the Readme file, but I think its good enough to continue.

2023-12-27 17:47 UTC, ManuelE-Osorio commented
Seems codacy just got stuck, because it hasn't started the analysis  .

2023-12-27 17:48 UTC, ManuelE-Osorio commented
Seems codacy just got stuck.

2024-01-08 06:31 UTC, TheCSharpAcademy requested changes
@ManuelE-Osorio My apologies for the delay. 🥺 I'm getting this error when deleting a stack:

![image](https://github.com/TheCSharpAcademy/CodeReviews.Console.Flashcards/assets/108711476/ffb1b0c3-bbaf-44d8-8efe-794272f44c75)

2024-01-08 08:37 UTC, ManuelE-Osorio commented on FlashCards.ManuelE-Osorio/Flashcards/Controllers/DataController.cs
>                  if (SelectedStack?.StackName == stackName)
Fixed bug in line 241

2024-01-08 08:41 UTC, ManuelE-Osorio commented
Fixed the bug. I was passing the Selected Stack and not the user input to the delete method. Also Codacy seems to be working now haha

2024-01-09 00:18 UTC, TheCSharpAcademy commented
@ManuelE-Osorio Great project, well done! 🤓 I think the only thing I could have added is more clarification regards to selecting a stack. You could keep an UI element so the users now which stacks are selected at any point in time (if any).

2024-01-09 00:18 UTC, merged