Project finished
TheCSharpAcademy/CodeReviews.Console.Flashcards pull request #88
Opened 2024-08-16 15:14 UTC by jollejonas

Looking forward to your review, thanks 😄

2024-10-09 05:12 UTC, TheCSharpAcademy commented
@jollejonas Have you submitted the project in the academy?

2024-12-13 01:22 UTC, jollejonas commented
@TheCSharpAcademy 
When i try to submit the project in the academy it already says that it has been completed, but it doesn't show as completed in my dashboard 😞

2025-01-30 09:38 UTC, chrisjamiecarter requested changes
Hey @jollejonas 👋,

Excellent work on your **Flashcards** project submission 🎉!

I have performed a peer review. Review/ignore any comments as you wish.

***

🟠 **Solution Structure**

💡 As per the academy's [Code Reviews](https://thecsharpacademy.com/article/52/code-reviews) page. I was expecting your project submission to be contained in a folder in the format: `[ProjectName].[GitHubUserName]`.

👨‍🏫 For example, `Flashcards.jollejonas`

💭 This will make it easier for code-reviewers to pull down and review your code in the future. This will also make sense when you get to the projects with other students code in.


🟠 **Style Guide Compliance**

💡 Remember that when you have finished a project, give it a polish pass. Refer to the Academy's [code-conventions](https://thecsharpacademy.com/article/58/code-conventions) page.

💭 This is important as good code conventions/styling ensures consistency, makes your code easier for others to read and maintain, and improves your chances of getting a pull request reviewed and approved.


🟠 **README File**

💡 One way to take your submission to the next level is by including a README file. This small addition can make a big difference!


🟠 **User Experience**

💡 Instead of making the user remember what they are updating. It might be better to show the original entity and then ask the user to provide updated values. 
Also, maybe give the option to keep the current value.
Also, give the option to cancel before choosing an option to update.

![image](https://github.com/user-attachments/assets/fa91b9cd-5598-49f2-8772-30a33a126053)


🔴 **Missing Requirement**

![image](https://github.com/user-attachments/assets/97c3a054-c94e-4b81-a7db-3459d6e5113e)

![image](https://github.com/user-attachments/assets/afeff2d6-eb5f-4eda-bbfe-a6deed150fa1)

***

🔧 Please revisit to try understand and fix any issues marked 🔴, as they block my approval.

Feel free to reach out if you have any questions or if you'd like to collaborate further on any of these points 🆘 .

I will go ahead and wait for you to make your changes, commit and push (which will then notify me) 😊 !

Thanks,
@chrisjamiecarter 👍

2025-01-30 09:38 UTC, chrisjamiecarter commented on jollejonas.Flashcards/jollejonas.Flashcards/Properties/appsettings.json
> +    "DefaultConnection": "Server=(localdb)\\mssqllocaldb;Database=Flashcards;Trusted_Connection=True;MultipleActiveResultSets=true"
🟢 **Database Configuration**

⭐

2025-01-30 09:38 UTC, chrisjamiecarter commented on jollejonas.Flashcards/jollejonas.Flashcards/DTOs/CardStackDetailsDTO.cs
> +﻿namespace jollejonas.Flashcards.DTOs
🟠 **Namespaces**
As per the academy's [code-conventions](https://thecsharpacademy.com/article/58/code-conventions) - Use the newest namespaces.
Use file-scoped namespaces to save an indentation level:

❌ 
```
// Block-Scoped Namespace
namespace YourNamespace
{
    // Code here...
}
```

✔️ 
```
// File-Scoped Namespace
namespace YourNamespace;

// Code here...
```

2025-01-30 09:38 UTC, chrisjamiecarter commented on jollejonas.Flashcards/jollejonas.Flashcards/Data/DatabaseManager.cs
> +            using var connection = GetConnection();
🟢 **Using Connections**

⭐

2025-01-30 09:38 UTC, chrisjamiecarter commented on jollejonas.Flashcards/jollejonas.Flashcards/Data/DatabaseManager.cs
> +            using var command = new SqlCommand(query, connection);
🟢 **Using Commands**

⭐

2025-01-30 09:38 UTC, chrisjamiecarter commented on jollejonas.Flashcards/jollejonas.Flashcards/Data/DatabaseManager.cs
> +                    command.Parameters.AddWithValue("@question", question);
🟢 **Parameterised SQL Queries**

⭐

2025-01-30 09:38 UTC, chrisjamiecarter commented on jollejonas.Flashcards/jollejonas.Flashcards/Data/DatabaseManager.cs
> +                IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'Flashcards')
🟠 **Hardcoded Database Name**

💡 You give the illusion of choice by allowing the user to set a `ConnectionString` in `appsettings.json`. Here I like to set the Database Name to `[Project]_[Student]`, so `Flashcards_jollejonas`. This configuration setting would be ignored in this `EnsureDatabaseExists` method, and use `Flashcards` instead.

2025-01-30 09:38 UTC, chrisjamiecarter commented on jollejonas.Flashcards/jollejonas.Flashcards/Services/StudySessionService.cs
> +                .AddChoices(2024)
🟠 **Future Proof**

💡 Useless for a new user as we are now in 2025...

2025-01-30 09:38 UTC, chrisjamiecarter commented on jollejonas.Flashcards/jollejonas.Flashcards/Program.cs
> +string? connectionString = configuration.GetConnectionString("DefaultConnection");
🟡 **Missing Connection String Behaviour**

💭 Your app cannot work without a connection string. One convention people do is to throw an exception if no connection string is found.

👨‍🏫 
`string? connectionString = configuration.GetConnectionString("DefaultConnection");` 
=>
`string connectionString = configuration.GetConnectionString("DefaultConnection") ?? throw new InvalidOperationException("Connection string 'DefaultConnection' not found.");`

2025-01-30 09:38 UTC, chrisjamiecarter commented on jollejonas.Flashcards/jollejonas.Flashcards/Data/DatabaseManager.cs
> +            ExecuteNonQuery(query);
🟠 **Throws Exception**

💡 This currently throws an exception if the database doesn't exist.

🔧 You need to use a connection string with the database removed.

![image](https://github.com/user-attachments/assets/8e8bdfb8-86d8-4e30-af83-e3e1a19bafe4)

2025-02-04 10:06 UTC, chrisjamiecarter requested changes
Hey @jollejonas 👋,

Great effort in getting you updates pushed through 💪!

Unfortunately, I have uncovered three new issue that need addressing 🔧.

***

🔴 **Missing Requirement**

Stack names should be unique, and I can easily enter a duplicate.

![image](https://github.com/user-attachments/assets/3528ef9a-0530-459a-9763-d3310fd5b894)

![image](https://github.com/user-attachments/assets/8ebbce29-46ee-45f9-8a78-83e02d0d0821)

🔴 **Cancel Button**

After selected the `Edit a card` menu option, then choosing `Cancel`, an exception is thrown and the app crashes.

![image](https://github.com/user-attachments/assets/27ae823d-0f2a-438d-aab5-607b141f56ee)

🔴 **App only works once**

It seems to be trying to seed data on every startup, and throwing an exception. I had to comment out the SeedData() line to get it to run.

![image](https://github.com/user-attachments/assets/0f92f585-df4f-4f45-b3b5-47d7e9ef2919)

***

🔧 Please revisit to try understand and fix any issues marked 🔴, as they block my approval.

Feel free to reach out if you have any questions or if you'd like to collaborate further on any of these points 🆘 .

I will go ahead and wait for you to make your changes, commit and push (which will then notify me) 😊 !

Thanks,
@chrisjamiecarter 👍

2025-02-04 12:11 UTC, jollejonas commented
Thanks a lot for the review! It helps a lot that you explain everything so well. 
The last bugs and missing requirements should have been fixed now. 🤞

2025-02-05 09:54 UTC, chrisjamiecarter requested changes
Hey @jollejonas 👋,

Nearly there 🏁!

Just one issue to fix and you should be done 🥅

Thanks
@chrisjamiecarter 👍

2025-02-05 09:54 UTC, chrisjamiecarter commented on Flashcards.jollejonas/Flashcards.jollejonas/Data/DatabaseManager.cs
> +        var result = command.ExecuteScalar();
🟠 **Incorrect Method**

❗ Note that seeding is not a requirement, so I you do not have to concentrate on this is you don't wish to.

💡 If you read the documentation, this executes a query and returns the first column of the first row of the result set... If you run your query in a dbms you will see that no result sets are returned! Meaning this will never trigger.

👨‍🏫 What you should have done is split your seed data query up. Instead of doing a massive query doing a hundred things. Everything starts with `Stacks`? So get the result of `SELECT Id FROM Stacks WHERE Name = 'C# Basics';`. If you get null back you know it doesn't exists and then you can seed that stack, cards and sessions. Then do the same for the next stacks and so on.

2025-02-05 09:54 UTC, chrisjamiecarter commented on Flashcards.jollejonas/Flashcards.jollejonas/Services/CardStackService.cs
> +            if (CheckIfStackExists(name))
🔴 **Add Method?**

💡 I can see that you check for duplicates in the `EditCard` method... But what about the `AddCard` method? 😆 

💭 Remember to handle case sensitivity.

![image](https://github.com/user-attachments/assets/8fdeda92-2056-47be-9eaf-3814c3c91988)

2025-02-07 09:40 UTC, chrisjamiecarter approved these changes
Hey @jollejonas 👋,

Great perseverance 🏃! Well done 🥇 


🟢 **Requirements**

⭐ You have fulfilled all of the project requirements!


I will go ahead and mark as approved, keep up the excellent work on the next projects! 😊

Best regards,
@chrisjamiecarter 👍

2025-02-07 09:41 UTC, closed without merging